fix_ci

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,6 +1,7 @@
 name: Build docker image
 on:
   push:
+  workflow_dispatch:
 
 jobs:
   set_build_id:
@@ -22,17 +23,14 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - name: Start BuildKit with custom MTU
-      run: |
-        docker run -d --name buildkitd-custom \
-          --privileged \
-          --network host \
-          -e BUILDKITD_FLAGS="--oci-worker-net=host" \
-          moby/buildkit:latest
+    - name: Create custom mtu Docker network
+      run: docker network create --opt com.docker.network.driver.mtu=1400 custom_mtu_network
 
-    - name: Create buildx builder
-      run: |
-        docker buildx create --driver docker-container --use
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
+      with:
+        driver-opts: |
+          network=custom_mtu_network
 
     - name: Login to Docker Hub
       uses: docker/login-action@v2
@@ -43,13 +41,26 @@ jobs:
     - name: Build and push
       uses: docker/build-push-action@v6
       with:
-        builder: custombuilder
+        # builder: custombuilder
         push: true
         tags: neonlabsorg/asap:${{ needs.set_build_id.outputs.build_id }}
+        network: custom_mtu_network
 
-    - name: Cleanup
-      if: always()
-      run: |
-        docker buildx rm custombuilder || true
-        docker rm -f buildkitd-custom || true
+    # - name: Cleanup
+    #   if: always()
+    #   run: |
+    #     docker buildx rm custombuilder || true
+    #     docker rm -f buildkitd-custom || true
 
+
+    # - name: Start BuildKit with custom MTU
+    #   run: |
+    #     docker run -d --name buildkitd-custom \
+    #       --privileged \
+    #       --network host \
+    #       -e BUILDKITD_FLAGS="--oci-worker-net=host" \
+    #       moby/buildkit:latest
+
+    # - name: Create buildx builder
+    #   run: |
+    #     docker buildx create --driver docker-container --use
